export const EDIT_THE_NODE = 'EDIT_THE_NODE';
export const FORMAT_NODE = 'FORMAT_NODE';
export const CHANGE_LINE_ANIMATED = 'CHANGE_ANIMATED_LINE';
export const CHANGE_DOTED_LINE_ANIMATED = 'CHANGE_DOTED_LINE_ANIMATED';
export const ADD_TAB = 'ADD_TAB';
export const UPDATE_DATA_SET = 'UPDATE_DATA_SET';
export const UPDATE_NODE_COLOR = 'UPDATE_NODE_COLOR';
export const ON_ELEMENT_CLICK_HANDLER = 'ON_ELEMENT_CLICK_HANDLER';
